[build]
  # This command 1. Creates the key file, 2. Installs Python tools, 3. Builds the site
  command = 'echo "$GOOGLE_CREDENTIALS" > shrish-credentials.json && pip install -r requirements.txt && python build.py'
  publish = "."

[dev]
  command = "python build.py"